name: dockerhub-mirror

on:
  workflow_dispatch:
    inputs:
      dockerhub-repo:
        description: 'DockerHub 的镜像仓库地址（如：nginx 或 aurorxa/nginx）'
        required: true
      dest-registry:
        description: '目标镜像仓库的地址 (eg. quay.io)'
        required: true
        default: 'quay.io'
      dest-repo:
        description: '目标镜像地址 (eg. aurorxa/nginx)'
        required: true
      dry-run:
        description: '是否 dry run ?'
        required: false
        default: 'false'

jobs:
  # 任务名称
  dockerhub-mirror:
    # 运行环境  
    runs-on: ubuntu-latest
    steps:
      - name: '安装 QEMU'
        uses: docker/setup-qemu-action@v2
      - name: '安装 Docker Buildx'
        uses: docker/setup-buildx-action@v2
      - name: '登录到 DockerHub 镜像仓库中'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: '登录到 ${{ github.event.inputs.dest-registry }} 镜像仓库中'
        uses: docker/login-action@v2
        with:
          registry: ${{ github.event.inputs.dest-registry }}
          username: ${{ secrets.DEST_USERNAME }}
          password: ${{ secrets.DEST_PASSWORD }}
      - name: '迁移 ${{ github.event.inputs.dockerhub-repo }} 到 ${{ github.event.inputs.dest-registry }}/${{ github.event.inputs.dest-repo }}'
        uses: crazy-max/ghaction-dockerhub-mirror@v1
        with:
          dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKER_PASSWORD }}
          dockerhub-repo: ${{ github.event.inputs.dockerhub-repo }}
          dest-registry: ${{ github.event.inputs.dest-registry }}
          dest-repo: ${{ github.event.inputs.dest-repo }}
          dry-run: ${{ github.event.inputs.dry-run }}
