name: volta-centos7
on:
  schedule:
    - cron: '30 23 5,15,30 * *'
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      voltaVersion:
        type: string
        description: "请输入volta的版本，如果没有输入，默认就是最新版本"
        default: 'latest'

env:
  REGISTRY: '' # 如果为空，则使用 DockerHUb
  IMAGE_NAME: volta
  VERSION: ${{inputs.voltaVersion }} 


jobs:
  build:
    # 运行环境 
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - name: "拉取仓库代码"
        uses: actions/checkout@v3
      - name: "安装除PR之外的cosign工具"
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: 'v1.11.0'
      - name: "安装qemu"
        uses: docker/setup-qemu-action@v2    
      - name: "安装Docker buildx"
        uses: docker/setup-buildx-action@v2
      - name: "登录Docker Hub 之类的容器仓库" 
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "构建和发布指定版本的Docker镜像"
        if: ${{ env.VERSION != '' }}
        id: build-specify-version-and-push
        uses: docker/build-push-action@v3
        with:
          context: ./ubuntu/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-centos7
          build-args: |
            VERSION: ${{ env.VERSION }}
      - name: "签署已发布的制定本版本Docker映像"
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-specify-version-and-push.outputs.digest }}            
      - name: "构建和发布最新版本的Docker镜像"
        if: ${{ env.VERSION == '' }}
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ./ubuntu/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest-centos7
          build-args: |
            VERSION: latest            
      - name: "签署已发布的Docker映像"
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
